version: "3.7"
services:
  fix-insencitive-import:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "5000:5000"
    container_name: fix-insencitive-import
    restart: always
    command: tail -F anything
    volumes:
      - "/usr/src/app/node_modules"
      - "./:/usr/src/app"